theme: jekyll-theme-cayman
title: 'Will Perry'
description: 'Software Engineer'
repository: 'thefridge111/thefridge111.github.io'
             
# Plugins have been moved into a gemfile where they should be.
# plugins:
#   - jekyll-livereload
#   - jekyll-theme-cayman
